SRC = circle.cpp rectangle.cpp shapes.cpp main.cpp shape_factory.cpp
OBJ = $(addsuffix .o,$(basename $(SRC))) 
CC = g++
CFLAGS = -c -g -Wall -Werror -pedantic
EXE = shape_factory

.PHONY : clean all

all : $(EXE)

shape_factory : $(OBJ)
		$(CC) -o $(EXE) $(OBJ)

$(OBJ) : %.o : %.cpp
		$(CC) $(CFLAGS) $<

#shapes.o : shapes.cpp shapes.h
#		g++ -c shapes.cpp

#circle.o : circle.cpp circle.h
#		g++ -c circle.cpp
	
#rectangle.o : rectangle.cpp rectangle.h
#		g++ -c rectangle.cpp


#main.o : main.cpp shapes.h rectangle.h circle.h
		g++ -c main.cpp		

clean :
		del *.o *.exe $(EXE)
