.PHONY : clean all

all : Uno

Uno : card.o users.o game.o main.o
		g++ -g  users.o card.o main.o game.o -o Uno -static-libstdc++ -static-libgcc -static


users.o : users.cpp users.h card.h 
		g++ -g -c users.cpp -static-libstdc++ -static-libgcc -static

card.o : card.cpp card.h color.hpp
		g++ -g -c card.cpp -static-libstdc++ -static-libgcc -static

game.o : game.cpp game.h users.h card.h 
		g++ -g -c game.cpp -static-libstdc++ -static-libgcc -static

main.o : main.cpp game.h users.h card.h 
		g++ -g -c main.cpp -static-libstdc++ -static-libgcc -static

clean : 	
		del *.o *.exe *.gch Uno

