.PHONY : clean all

all : Uno

Uno : card.o users.o game.o main.o 
		g++ -g  users.o card.o main.o game.o -o Uno


users.o : users.cpp card.cpp users.h card.h
		g++ -g -c users.cpp card.cpp

card.o : card.cpp card.h
		g++ -c card.cpp

game.o : game.cpp users.cpp card.cpp game.h users.h card.h
		g++ -g -c game.cpp users.cpp card.cpp

main.o : main.cpp game.h users.h card.h
		g++ -g -c main.cpp

clean : 	
		del *.o *.exe Uno

